version: '3'

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'stori-database'
    environment:
      MONGO_INITDB_ROOT_USERNAME: stori
      MONGO_INITDB_ROOT_PASSWORD: stori
    volumes:
      - mongovolume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=stori
      - ME_CONFIG_MONGODB_ADMINPASSWORD=stori
      - ME_CONFIG_MONGODB_URL=mongodb://stori:stori@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
volumes:
  mongovolume:
    external: false