version: '3'

services:
  email-ms:
    build: 
      dockerfile: Dockerfile.localdev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 5001:5001
      - 9092:9092
    networks:
      - email-ms-network

  mailhog:
    image: 'mailhog/mailhog:latest'
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - email-ms-network

networks:
  email-ms-network:
    driver: bridge
    name: grpc_network